repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args: [--fix] # ruff will automatically fix some issues if possible
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.3
    hooks:
      - id: uv-lock
      - id: uv-export
        args: [--frozen, --no-dev, --no-hashes, -o=requirements.txt]
