repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args: [--fix] # ruff will automatically fix some issues if possible
      - id: ruff-format
