[tool.poetry]
name = "md4help-center"
version = "0.1.0"
description = "Make mds for LLMs from Zendesk help center"
authors = ["Tuhacrt"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
markdownify = "^1.1.0"
dotenv = "^0.9.9"
requests = "^2.32.3"


[tool.poetry.group.dev.dependencies]
ruff = "0.11.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
